=== anchore/syft/schema/json/schema-1.0.4.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/Document",
  "definitions": {
    "ApkFileRecord": {
      "required": [
        "path"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "ownerUid": {
          "type": "string"
        },
        "ownerGid": {
          "type": "string"
        },
        "permissions": {
          "type": "string"
        },
        "checksum": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "ApkMetadata": {
      "required": [
        "package",
        "originPackage",
        "maintainer",
        "version",
        "license",
        "architecture",
        "url",
        "description",
        "size",
        "installedSize",
        "pullDependencies",
        "pullChecksum",
        "gitCommitOfApkPort",
        "files"
      ],
      "properties": {
        "package": {
          "type": "string"
        },
        "originPackage": {
          "type": "string"
        },
        "maintainer": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "license": {
          "type": "string"
        },
        "architecture": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "size": {
          "type": "integer"
        },
        "installedSize": {
          "type": "integer"
        },
        "pullDependencies": {
          "type": "string"
        },
        "pullChecksum": {
          "type": "string"
        },
        "gitCommitOfApkPort": {
          "type": "string"
        },
        "files": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/ApkFileRecord"
          },
          "type": "array"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "CargoPackageMetadata": {
      "required": [
        "name",
        "version",
        "source",
        "checksum",
        "dependencies"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "checksum": {
          "type": "string"
        },
        "dependencies": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Descriptor": {
      "required": [
        "name",
        "version"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "configuration": {
          "additionalProperties": true
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Digest": {
      "required": [
        "algorithm",
        "value"
      ],
      "properties": {
        "algorithm": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Distribution": {
      "required": [
        "name",
        "version",
        "idLike"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "idLike": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Document": {
      "required": [
        "artifacts",
        "artifactRelationships",
        "source",
        "distro",
        "descriptor",
        "schema"
      ],
      "properties": {
        "fileMetadata": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/FileMetadata"
          },
          "type": "array"
        },
        "artifacts": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/Package"
          },
          "type": "array"
        },
        "artifactRelationships": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/Relationship"
          },
          "type": "array"
        },
        "source": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Source"
        },
        "distro": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Distribution"
        },
        "descriptor": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Descriptor"
        },
        "schema": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Schema"
        },
        "artifacts.metadata": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/ApkMetadata"
            },
            {
              "$ref": "#/definitions/CargoPackageMetadata"
            },
            {
              "$ref": "#/definitions/DpkgMetadata"
            },
            {
              "$ref": "#/definitions/GemMetadata"
            },
            {
              "$ref": "#/definitions/JavaMetadata"
            },
            {
              "$ref": "#/definitions/NpmPackageJSONMetadata"
            },
            {
              "$ref": "#/definitions/PythonPackageMetadata"
            },
            {
              "$ref": "#/definitions/RpmdbMetadata"
            }
          ]
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "DpkgFileRecord": {
      "required": [
        "path",
        "md5"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "md5": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "DpkgMetadata": {
      "required": [
        "package",
        "source",
        "version",
        "sourceVersion",
        "architecture",
        "maintainer",
        "installedSize",
        "files"
      ],
      "properties": {
        "package": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "sourceVersion": {
          "type": "string"
        },
        "architecture": {
          "type": "string"
        },
        "maintainer": {
          "type": "string"
        },
        "installedSize": {
          "type": "integer"
        },
        "files": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/DpkgFileRecord"
          },
          "type": "array"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "FileMetadata": {
      "required": [
        "location",
        "metadata"
      ],
      "properties": {
        "location": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Location"
        },
        "metadata": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/FileMetadataEntry"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "FileMetadataEntry": {
      "required": [
        "mode",
        "type",
        "userID",
        "groupID"
      ],
      "properties": {
        "mode": {
          "type": "integer"
        },
        "type": {
          "type": "string"
        },
        "linkDestination": {
          "type": "string"
        },
        "userID": {
          "type": "integer"
        },
        "groupID": {
          "type": "integer"
        },
        "digests": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/Digest"
          },
          "type": "array"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "GemMetadata": {
      "required": [
        "name",
        "version"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "files": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "authors": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "licenses": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "homepage": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "JavaManifest": {
      "properties": {
        "main": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "namedSections": {
          "patternProperties": {
            ".*": {
              "patternProperties": {
                ".*": {
                  "type": "string"
                }
              },
              "type": "object"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "JavaMetadata": {
      "required": [
        "virtualPath"
      ],
      "properties": {
        "virtualPath": {
          "type": "string"
        },
        "manifest": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/JavaManifest"
        },
        "pomProperties": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/PomProperties"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Location": {
      "required": [
        "path"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "layerID": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "NpmPackageJSONMetadata": {
      "required": [
        "author",
        "licenses",
        "homepage",
        "description",
        "url"
      ],
      "properties": {
        "files": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "author": {
          "type": "string"
        },
        "licenses": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "homepage": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Package": {
      "required": [
        "id",
        "name",
        "version",
        "type",
        "foundBy",
        "locations",
        "licenses",
        "language",
        "cpes",
        "purl",
        "metadataType",
        "metadata"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "foundBy": {
          "type": "string"
        },
        "locations": {
          "items": {
            "$ref": "#/definitions/Location"
          },
          "type": "array"
        },
        "licenses": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "language": {
          "type": "string"
        },
        "cpes": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "purl": {
          "type": "string"
        },
        "metadataType": {
          "type": "string"
        },
        "metadata": {
          "additionalProperties": true
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "PomProperties": {
      "required": [
        "path",
        "name",
        "groupId",
        "artifactId",
        "version",
        "extraFields"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "groupId": {
          "type": "string"
        },
        "artifactId": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "extraFields": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "PythonFileDigest": {
      "required": [
        "algorithm",
        "value"
      ],
      "properties": {
        "algorithm": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "PythonFileRecord": {
      "required": [
        "path"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "digest": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/PythonFileDigest"
        },
        "size": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "PythonPackageMetadata": {
      "required": [
        "name",
        "version",
        "license",
        "author",
        "authorEmail",
        "platform",
        "sitePackagesRootPath"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "license": {
          "type": "string"
        },
        "author": {
          "type": "string"
        },
        "authorEmail": {
          "type": "string"
        },
        "platform": {
          "type": "string"
        },
        "files": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/PythonFileRecord"
          },
          "type": "array"
        },
        "sitePackagesRootPath": {
          "type": "string"
        },
        "topLevelPackages": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Relationship": {
      "required": [
        "parent",
        "child",
        "type",
        "metadata"
      ],
      "properties": {
        "parent": {
          "type": "string"
        },
        "child": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "metadata": {
          "additionalProperties": true
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "RpmdbFileRecord": {
      "required": [
        "path",
        "mode",
        "size",
        "sha256"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "mode": {
          "type": "integer"
        },
        "size": {
          "type": "integer"
        },
        "sha256": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "RpmdbMetadata": {
      "required": [
        "name",
        "version",
        "epoch",
        "architecture",
        "release",
        "sourceRpm",
        "size",
        "license",
        "vendor",
        "files"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "epoch": {
          "type": "integer"
        },
        "architecture": {
          "type": "string"
        },
        "release": {
          "type": "string"
        },
        "sourceRpm": {
          "type": "string"
        },
        "size": {
          "type": "integer"
        },
        "license": {
          "type": "string"
        },
        "vendor": {
          "type": "string"
        },
        "files": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/RpmdbFileRecord"
          },
          "type": "array"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Schema": {
      "required": [
        "version",
        "url"
      ],
      "properties": {
        "version": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "type": "object"
    },
    "Source": {
      "required": [
        "type",
        "target"
      ],
      "properties": {
        "type": {
          "type": "string"
        },
        "target": {
          "additionalProperties": true
        }
      },
      "additionalProperties": true,
      "type": "object"
    }
  }
}

=== anchore/syft/syft/format/test-fixtures/alpine-syft.json
{
 "artifacts": [
  {
   "id": "880965c7-95ff-483c-80bb-22799bbbee63",
   "name": "alpine-baselayout",
   "version": "3.2.0-r16",
   "type": "apk",
   "foundBy": "apkdb-cataloger",
   "locations": [
    {
     "path": "/lib/apk/db/installed",
     "layerID": "sha256:e2eb06d8af8218cfec8210147357a68b7e13f7c485b991c288c2d01dc228bb68"
    }
   ],
   "licenses": [
    "GPL-2.0-only"
   ],
   "language": "",
   "cpes": [
    "cpe:2.3:a:alpine-baselayout:alpine-baselayout:3.2.0-r16:*:*:*:*:*:*:*",
    "cpe:2.3:a:alpine-baselayout:alpine_baselayout:3.2.0-r16:*:*:*:*:*:*:*",
    "cpe:2.3:a:alpine_baselayout:alpine-baselayout:3.2.0-r16:*:*:*:*:*:*:*",
    "cpe:2.3:a:alpine_baselayout:alpine_baselayout:3.2.0-r16:*:*:*:*:*:*:*",
    "cpe:2.3:a:alpine:alpine-baselayout:3.2.0-r16:*:*:*:*:*:*:*",
    "cpe:2.3:a:alpine:alpine_baselayout:3.2.0-r16:*:*:*:*:*:*:*"
   ],
   "purl": "pkg:apk/alpine/alpine-baselayout@3.2.0-r16?arch=x86_64",
   "metadataType": "ApkMetadata",
   "metadata": {
    "package": "alpine-baselayout",
    "originPackage": "alpine-baselayout",
    "maintainer": "Natanael Copa <ncopa@alpinelinux.org>",
    "version": "3.2.0-r16",
    "license": "GPL-2.0-only",
    "architecture": "x86_64",
    "url": "https://git.alpinelinux.org/cgit/aports/tree/main/alpine-baselayout",
    "description": "Alpine base dir structure and init scripts",
    "size": 20716,
    "installedSize": 413696,
    "pullDependencies": "/bin/sh so:libc.musl-x86_64.so.1",
    "pullChecksum": "Q1UJtB9cNV4r+/VbxySkEei++qbho=",
    "gitCommitOfApkPort": "8a8c96a0ea2fcd824c361aa4438763fa33ee8ca0",
    "files": [
     {
      "path": "/dev"
     },
     {
      "path": "/dev/pts"
     },
     {
      "path": "/dev/shm"
     },
     {
      "path": "/etc"
     },
     {
      "path": "/etc/fstab",
      "digest": {
       "algorithm": "sha1",
       "value": "Q11Q7hNe8QpDS531guqCdrXBzoA/o="
      }
     },
     {
      "path": "/etc/group",
      "digest": {
       "algorithm": "sha1",
       "value": "Q13K+olJg5ayzHSVNUkggZJXuB+9Y="
      }
     },
     {
      "path": "/etc/hostname",
      "digest": {
       "algorithm": "sha1",
       "value": "Q16nVwYVXP/tChvUPdukVD2ifXOmc="
      }
     },
     {
      "path": "/etc/hosts",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1BD6zJKZTRWyqGnPi4tSfd3krsMU="
      }
     },
     {
      "path": "/etc/inittab",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1TsthbhW7QzWRe1E/NKwTOuD4pHc="
      }
     },
     {
      "path": "/etc/modules",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1toogjUipHGcMgECgPJX64SwUT1M="
      }
     },
     {
      "path": "/etc/motd",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1XmduVVNURHQ27TvYp1Lr5TMtFcA="
      }
     },
     {
      "path": "/etc/mtab",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "777",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1kiljhXXH1LlQroHsEJIkPZg2eiw="
      }
     },
     {
      "path": "/etc/passwd",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1TchuuLUfur0izvfZQZxgN/LJhB8="
      }
     },
     {
      "path": "/etc/profile",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1VmHPWPjjvz4oCsbmYCUB4uWpSkc="
      }
     },
     {
      "path": "/etc/protocols",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1omKlp3vgGq2ZqYzyD/KHNdo8rDc="
      }
     },
     {
      "path": "/etc/services",
      "digest": {
       "algorithm": "sha1",
       "value": "Q19WLCv5ItKg4MH7RWfNRh1I7byQc="
      }
     },
     {
      "path": "/etc/shadow",
      "ownerUid": "0",
      "ownerGid": "42",
      "permissions": "640",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1ltrPIAW2zHeDiajsex2Bdmq3uqA="
      }
     },
     {
      "path": "/etc/shells",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1ojm2YdpCJ6B/apGDaZ/Sdb2xJkA="
      }
     },
     {
      "path": "/etc/sysctl.conf",
      "digest": {
       "algorithm": "sha1",
       "value": "Q14upz3tfnNxZkIEsUhWn7Xoiw96g="
      }
     },
     {
      "path": "/etc/apk"
     },
     {
      "path": "/etc/conf.d"
     },
     {
      "path": "/etc/crontabs"
     },
     {
      "path": "/etc/crontabs/root",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "600",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1vfk1apUWI4yLJGhhNRd0kJixfvY="
      }
     },
     {
      "path": "/etc/init.d"
     },
     {
      "path": "/etc/modprobe.d"
     },
     {
      "path": "/etc/modprobe.d/aliases.conf",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1WUbh6TBYNVK7e4Y+uUvLs/7viqk="
      }
     },
     {
      "path": "/etc/modprobe.d/blacklist.conf",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1xxYGU6S6TLQvb7ervPrWWwAWqMg="
      }
     },
     {
      "path": "/etc/modprobe.d/i386.conf",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1pnay/njn6ol9cCssL7KiZZ8etlc="
      }
     },
     {
      "path": "/etc/modprobe.d/kms.conf",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1ynbLn3GYDpvajba/ldp1niayeog="
      }
     },
     {
      "path": "/etc/modules-load.d"
     },
     {
      "path": "/etc/network"
     },
     {
      "path": "/etc/network/if-down.d"
     },
     {
      "path": "/etc/network/if-post-down.d"
     },
     {
      "path": "/etc/network/if-pre-up.d"
     },
     {
      "path": "/etc/network/if-up.d"
     },
     {
      "path": "/etc/opt"
     },
     {
      "path": "/etc/periodic"
     },
     {
      "path": "/etc/periodic/15min"
     },
     {
      "path": "/etc/periodic/daily"
     },
     {
      "path": "/etc/periodic/hourly"
     },
     {
      "path": "/etc/periodic/monthly"
     },
     {
      "path": "/etc/periodic/weekly"
     },
     {
      "path": "/etc/profile.d"
     },
     {
      "path": "/etc/profile.d/README",
      "digest": {
       "algorithm": "sha1",
       "value": "Q135OWsCzzvnB2fmFx62kbqm1Ax1k="
      }
     },
     {
      "path": "/etc/profile.d/color_prompt.sh.disabled",
      "digest": {
       "algorithm": "sha1",
       "value": "Q10wL23GuSCVfumMRgakabUI6EsSk="
      }
     },
     {
      "path": "/etc/profile.d/locale.sh",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1S8j+WW71mWxfVy8ythqU7HUVoBw="
      }
     },
     {
      "path": "/etc/sysctl.d"
     },
     {
      "path": "/home"
     },
     {
      "path": "/lib"
     },
     {
      "path": "/lib/firmware"
     },
     {
      "path": "/lib/mdev"
     },
     {
      "path": "/lib/modules-load.d"
     },
     {
      "path": "/lib/sysctl.d"
     },
     {
      "path": "/lib/sysctl.d/00-alpine.conf",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1HpElzW1xEgmKfERtTy7oommnq6c="
      }
     },
     {
      "path": "/media"
     },
     {
      "path": "/media/cdrom"
     },
     {
      "path": "/media/floppy"
     },
     {
      "path": "/media/usb"
     },
     {
      "path": "/mnt"
     },
     {
      "path": "/opt"
     },
     {
      "path": "/proc"
     },
     {
      "path": "/root",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "700"
     },
     {
      "path": "/run"
     },
     {
      "path": "/sbin"
     },
     {
      "path": "/sbin/mkmntdirs",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "755",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1VcFI6coRl6HWWVShMW+G5Sb3JH8="
      }
     },
     {
      "path": "/srv"
     },
     {
      "path": "/sys"
     },
     {
      "path": "/tmp",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "1777"
     },
     {
      "path": "/usr"
     },
     {
      "path": "/usr/lib"
     },
     {
      "path": "/usr/lib/modules-load.d"
     },
     {
      "path": "/usr/local"
     },
     {
      "path": "/usr/local/bin"
     },
     {
      "path": "/usr/local/lib"
     },
     {
      "path": "/usr/local/share"
     },
     {
      "path": "/usr/sbin"
     },
     {
      "path": "/usr/share"
     },
     {
      "path": "/usr/share/man"
     },
     {
      "path": "/usr/share/misc"
     },
     {
      "path": "/var"
     },
     {
      "path": "/var/run",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "777",
      "digest": {
       "algorithm": "sha1",
       "value": "Q11/SNZz/8cK2dSKK+cJpVrZIuF4Q="
      }
     },
     {
      "path": "/var/cache"
     },
     {
      "path": "/var/cache/misc"
     },
     {
      "path": "/var/empty",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "555"
     },
     {
      "path": "/var/lib"
     },
     {
      "path": "/var/lib/misc"
     },
     {
      "path": "/var/local"
     },
     {
      "path": "/var/lock"
     },
     {
      "path": "/var/lock/subsys"
     },
     {
      "path": "/var/log"
     },
     {
      "path": "/var/mail"
     },
     {
      "path": "/var/opt"
     },
     {
      "path": "/var/spool"
     },
     {
      "path": "/var/spool/mail",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "777",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1dzbdazYZA2nTzSIG3YyNw7d4Juc="
      }
     },
     {
      "path": "/var/spool/cron"
     },
     {
      "path": "/var/spool/cron/crontabs",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "777",
      "digest": {
       "algorithm": "sha1",
       "value": "Q1OFZt+ZMp7j0Gny0rqSKuWJyqYmA="
      }
     },
     {
      "path": "/var/tmp",
      "ownerUid": "0",
      "ownerGid": "0",
      "permissions": "1777"
     }
    ]
   }
  },
  {
   "id": "8dbd8f4d-c13f-4120-8c2b-4596e5c46fce",
   "name": "alpine-keys",
   "version": "2.3-r1",
   "type": "apk",
   "foundBy": "apkdb-cataloger",
   "locations": [
    {
     "path": "/lib/apk/db/installed",
